apiVersion: apps/v1
kind: Deployment        
metadata:       
  name: applient-server   
spec:   
  replicas: 1   
  selector:     
    matchLabels:        
      type: server 
      service: applient        
  template:     
    metadata:   
      labels:   
        type: server       
        service: applient      
    spec:       
      containers:       
      - name: server       
        image: adnans22/applient-server:v1        
        env:    
        - name: model      
          value: applient-model   
        readinessProbe: 
          httpGet:      
            path: /hello   
            port: 5000  
          periodSeconds: 1      
        livenessProbe:  
          httpGet:      
            path: /hello   
            port: 5000
          periodSeconds: 60  
        resources:          
          requests:     
            memory: "5Mi"       
            cpu: 0.01   

---     

apiVersion: v1  
kind: Service   
metadata:       
  name: applient-server   
spec:   
  ports:        
  - port: 5000  
  selector:     
    type: server   
    service: applient